### ISSUE TITLE
is Transaction Ack Times correctly?

### ISSUE THREAD

**Issue by yichaosun** [phishman3579/Bitcoin#1]
hello bro,
I trace the source ,when it comes to transaction-ack,i found that if a transaction is acked,add it in a block, so ,didn't a transaction should be acked 6times?

and every transaction create a block?

and ,I do not trace the source totally, just in transaction ack, I wonder if the sample is like bitcoin totally, the logic is complete to what the bitcoin is

**Comment by phishman3579** [comment]
I'm not sure I understand the question.

**Comment by yichaosun** [comment]
thx for replay ,I'm not good at English, I will trace the source code for more information, thx so much!!!!

**Comment by phishman3579** [comment]
No problem, if you can give me an example in code (our universal language) it may be easier for me to understand.
