### ISSUE TITLE
Thanks for sharing!

### ISSUE THREAD

**Issue by JonathanRosado** [phishman3579/Bitcoin#2]
Currently trying to get into blockchain development and stumbled across this repo. I've followed a couple of tutorials where they simply implement a very crude version of PoW/Blockchain-- without wallets, without peers, etc. 

How far have you taken this project? Does it have a full blown consensus algorithm where peers participate?

Again, thanks for sharing much needed material on this topic

**Comment by phishman3579** [comment]
If by "full blown consensus algorithm", you mean the Proof of Work algorithm with multiple peers then yes the code does have that feature. 

You can take a look at:
com.jwetherell.bitcoin.ProofOfWork.solve(MiningTask, byte[], long)
